<?php
// Welcome Email templates
Configure::set('Connectreseller.email_templates', [
    'en_us' => [
        'lang' => 'en_us',
        'text' => 'Your new domain is being processed and will be registered soon!

Domain: {service.domain}

Thank you for your business!',
        'html' => '<p>Your new domain is being processed and will be registered soon!</p>
<p>Domain: {service.domain}</p>
<p>Thank you for your business!</p>'
    ]
]);

// All available TLDs at date as 16/06/2024
Configure::set('Connectreseller.tlds', [
'.5G.in',
'.6G.in',
'.abogado',
'.ac',
'.academy',
'.accountant',
'.accountants',
'.actor',
'.adult',
'.ae',
'.ae.org',
'.agency',
'.ai',
'.ai.in',
'.airforce',
'.am.in',
'.apartments',
'.app',
'.archi',
'.army',
'.art',
'.asia',
'.associates',
'.attorney',
'.auction',
'.audio',
'.auto',
'.autos',
'.baby',
'.band',
'.bank',
'.bar',
'.bargains',
'.beauty',
'.beer',
'.best',
'.bet',
'.bh',
'.bible',
'.bid',
'.bihar.in',
'.bike',
'.bingo',
'.bio',
'.biz',
'.biz.bh',
'.biz.in',
'.black',
'.blackfriday',
'.blog',
'.blue',
'.boats',
'.bond',
'.boo',
'.boston',
'.boutique',
'.br.com',
'.broker',
'.build',
'.builders',
'.business',
'.business.in',
'.buzz',
'.ca.in',
'.cab',
'.cafe',
'.cam',
'.camera',
'.camp',
'.capital',
'.car',
'.cards',
'.care',
'.careers',
'.cars',
'.casa',
'.case',
'.cash',
'.casino',
'.catering',
'.cc',
'.cc.bh',
'.center',
'.ceo',
'.cfd',
'.charity',
'.chat',
'.cheap',
'.christmas',
'.church',
'.city',
'.claims',
'.cleaning',
'.click',
'.clinic',
'.clothing',
'.cloud',
'.club',
'.cn.com',
'.cn.in',
'.co',
'.co.com',
'.co.in',
'.co.nl',
'.co.no',
'.coach',
'.codes',
'.coffee',
'.college',
'.com',
'.com.bh',
'.com.de',
'.com.in',
'.com.ph',
'.com.se',
'.community',
'.company',
'.compare',
'.computer',
'.condos',
'.construction',
'.consulting',
'.contact',
'.contractors',
'.cooking',
'.cool',
'.coop',
'.coop.in',
'.country',
'.coupons',
'.courses',
'.credit',
'.creditcard',
'.cricket',
'.cruises',
'.cs.in',
'.cyou',
'.dance',
'.date',
'.dating',
'.day',
'.de.com',
'.dealer',
'.deals',
'.degree',
'.delhi.in',
'.delivery',
'.democrat',
'.dental',
'.dentist',
'.desi',
'.design',
'.dev',
'.diamonds',
'.diet',
'.digital',
'.direct',
'.directory',
'.discount',
'.DIY',
'.doctor',
'.dog',
'.domains',
'.download',
'.dr.in',
'.earth',
'.edu.bh',
'.education',
'.email',
'.energy',
'.engineer',
'.engineering',
'.enterprises',
'.equipment',
'.er.in',
'.estate',
'.eu.com',
'.events',
'.exchange',
'.expert',
'.exposed',
'.express',
'.fail',
'.faith',
'.family',
'.fan',
'.fans',
'.farm',
'.fashion',
'.feedback',
'.finance',
'.financial',
'.firm.in',
'.fish',
'.fishing',
'.fit',
'.fitness',
'.flights',
'.florist',
'.flowers',
'.fm',
'.fo',
'.food',
'.football',
'.forex',
'.forsale',
'.forum',
'.foundation',
'.frl',
'.fun',
'.fund',
'.furniture',
'.futbol',
'.fyi',
'.gallery',
'.game',
'.games',
'.garden',
'.gay',
'.gb.net',
'.gd',
'.gen.in',
'.gift',
'.gifts',
'.gives',
'.gl',
'.glass',
'.global',
'.gmbh',
'.gold',
'.golf',
'.gr.com',
'.graphics',
'.gratis',
'.green',
'.gripe',
'.group',
'.guide',
'.guitars',
'.gujarat.in',
'.guru',
'.hair',
'.haus',
'.health',
'.healthcare',
'.help',
'.hiv',
'.hockey',
'.holdings',
'.holiday',
'.homes',
'.horse',
'.hospital',
'.host',
'.hosting',
'.house',
'.hu.net',
'.icu',
'.immo',
'.immobilien',
'.in',
'.in.net',
'.inc',
'.ind.in',
'.industries',
'.info',
'.info.bh',
'.info.in',
'.ink',
'.institute',
'.insurance',
'.insure',
'.int.in',
'.international',
'.internet.in',
'.investments',
'.io',
'.io.in',
'.irish',
'.it.com',
'.jetzt',
'.jewelry',
'.jp.net',
'.jpn.com',
'.juegos',
'.kaufen',
'.KIDS',
'.kim',
'.kitchen',
'.land',
'.lat',
'.law',
'.lawyer',
'.lease',
'.legal',
'.lgbt',
'.life',
'.lifestyle',
'.lighting',
'.limited',
'.limo',
'.link',
'.live',
'.living',
'.llc',
'.loan',
'.loans',
'.lol',
'.london',
'.lotto',
'.love',
'.ltd',
'.luxe',
'.luxury',
'.maison',
'.makeup',
'.management',
'.market',
'.marketing',
'.markets',
'.mba',
'.me',
'.me.bh',
'.me.in',
'.med.bh',
'.media',
'.melbourne',
'.memorial',
'.men',
'.mex.com',
'.miami',
'.mobi',
'.moda',
'.moe',
'.mom',
'.money',
'.monster',
'.mortgage',
'.motorcycles',
'.movie',
'.name',
'.name.bh',
'.navy',
'.net',
'.net.bh',
'.net.in',
'.net.ph',
'.network',
'.new',
'.news',
'.ninja',
'.observer',
'.one',
'.online',
'.ooo',
'.org',
'.org.bh',
'.org.in',
'.org.ph',
'.organic',
'.osaka',
'.page',
'.paris',
'.partners',
'.parts',
'.party',
'.pet',
'.pg.in',
'.ph',
'.photo',
'.photography',
'.photos',
'.pics',
'.pictures',
'.pink',
'.pizza',
'.place',
'.plumbing',
'.plus',
'.poker',
'.porn',
'.post.in',
'.press',
'.pro.in',
'.productions',
'.promo',
'.properties',
'.property',
'.protection',
'.pub',
'.pw',
'.qpon',
'.quest',
'.racing',
'.radio.am',
'.radio.fm',
'.realty',
'.recipes',
'.red',
'.rehab',
'.reise',
'.reisen',
'.reit',
'.rent',
'.rentals',
'.repair',
'.report',
'.republican',
'.rest',
'.restaurant',
'.review',
'.reviews',
'.rip',
'.rocks',
'.rodeo',
'.rsvp',
'.ru.com',
'.run',
'.sa.com',
'.saarland',
'.sale',
'.salon',
'.sarl',
'.sbs',
'.school',
'.schule',
'.science',
'.se.net',
'.security',
'.select',
'.services',
'.sex',
'.sexy',
'.sh',
'.shabaka',
'.shoes',
'.shop',
'.shopping',
'.show',
'.singles',
'.site',
'.ski',
'.skin',
'.soccer',
'.social',
'.software',
'.solar',
'.solutions',
'.space',
'.storage',
'.store',
'.stream',
'.studio',
'.study',
'.style',
'.sucks',
'.supplies',
'.supply',
'.support',
'.surf',
'.surgery',
'.sydney',
'.systems',
'.tattoo',
'.tax',
'.taxi',
'.team',
'.tech',
'.technology',
'.tennis',
'.theater',
'.theatre',
'.tickets',
'.tienda',
'.tips',
'.tires',
'.today',
'.tools',
'.tours',
'.town',
'.toys',
'.trade',
'.trading',
'.training',
'.travel',
'.travel.in',
'.tv',
'.tv.in',
'.uk.com',
'.uk.in',
'.uk.net',
'.university',
'.uno',
'.up.in',
'.us',
'.us.com',
'.us.in',
'.us.org',
'.vacations',
'.vana',
'.vegas',
'.ventures',
'.vet',
'.vg',
'.viajes',
'.video',
'.villas',
'.vin',
'.vip',
'.vision',
'.vodka',
'.vote',
'.voyage',
'.vu',
'.watch',
'.webcam',
'.website',
'.wedding',
'.wiki',
'.win',
'.wine',
'.work',
'.works',
'.world',
'.ws',
'.wtf',
'.xxx',
'.xyz',
'.yachts',
'.yoga',
'.za.com',
'.zone',
]);

// Transfer fields
Configure::set('Connectreseller.transfer_fields', [
    'Websitename' => [
        'label' => Language::_('Connectreseller.transfer.Websitename', true),
        'type' => 'text'
    ],
    'Authcode' => [
        'label' => Language::_('Connectreseller.transfer.Authcode', true),
        'type' => 'text'
    ]
]);

// Domain fields
Configure::set('Connectreseller.domain_fields', [
    'Websitename' => [
        'label' => Language::_('Connectreseller.domain.Websitename', true),
        'type' => 'text'
    ]
]);

// Nameserver fields
Configure::set('Connectreseller.nameserver_fields', [
    'ns1' => [
        'label' => Language::_('Connectreseller.nameserver.ns1', true),
        'type' => 'text'
    ],
    'ns2' => [
        'label' => Language::_('Connectreseller.nameserver.ns2', true),
        'type' => 'text'
    ],
    'ns3' => [
        'label' => Language::_('Connectreseller.nameserver.ns3', true),
        'type' => 'text'
    ],
    'ns4' => [
        'label' => Language::_('Connectreseller.nameserver.ns4', true),
        'type' => 'text'
    ]
]);

// Whois fields
Configure::set('Connectreseller.whois_fields', [
    'Name' => [
        'label' => Language::_('Connectreseller.whois.Name', true),
        'type' => 'text'
    ],
    'EmailAddress' => [
        'label' => Language::_('Connectreseller.whois.EmailAddress', true),
        'type' => 'text'
    ],
    'Address1' => [
        'label' => Language::_('Connectreseller.whois.Address', true),
        'type' => 'text'
    ],
    'City' => [
        'label' => Language::_('Connectreseller.whois.City', true),
        'type' => 'text'
    ],
    'StateName' => [
        'label' => Language::_('Connectreseller.whois.StateName', true),
        'type' => 'text'
    ],
    'CountryName' => [
        'label' => Language::_('Connectreseller.whois.CountryName', true),
        'type' => 'text'
    ],
    'ZipCode' => [
        'label' => Language::_('Connectreseller.whois.Zip', true),
        'type' => 'text'
    ],
    'PhoneNo' => [
        'label' => Language::_('Connectreseller.whois.PhoneNo', true),
        'type' => 'text'
    ]
]);

// .US
Configure::set('Connectreseller.domain_fields.us', [
    'nexusCategory' => [
        'label' => Language::_('Connectreseller.domain_fields.category', true),
        'type' => 'select',
        'options' => [
            'C11' => Language::_('Connectreseller.domain_fields.category.c11', true),
            'C12' => Language::_('Connectreseller.domain_fields.category.c12', true),
            'C21' => Language::_('Connectreseller.domain_fields.category.c21', true),
            'C31' => Language::_('Connectreseller.domain_fields.category.c31', true),
            'C32' => Language::_('Connectreseller.domain_fields.category.c32', true)
        ]
    ],
    'appPurpose' => [
        'label' => Language::_('Connectreseller.domain_fields.purpose', true),
        'type' => 'select',
        'options' => [
            'P1' => Language::_('Connectreseller.domain_fields.purpose.p1', true),
            'P2' => Language::_('Connectreseller.domain_fields.purpose.p2', true),
            'P3' => Language::_('Connectreseller.domain_fields.purpose.p3', true),
            'P4' => Language::_('Connectreseller.domain_fields.purpose.p4', true),
            'P5' => Language::_('Connectreseller.domain_fields.purpose.p5', true)
        ]
    ],
    'isUs' => [
        'type' => 'hidden',
        'value' => '1'
    ]
]);
